# This is a basic workflow to help you get started with Actions

name: Process docs

# Controls when the workflow will run
on:
  push:
  #pull_request:
  #  branches: [ "main", "rc2" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: build metadata guide
        run: |
          python source/preprocess.py -i source/docs/minimal-guide.md -o minimal_metadata_guide.md
      - name: build yoda table
        run: |
          python source/preprocess.py -i source/docs/yoda-metadata-table.md -o Yoda/metadata_table.md
      - name: build osf table
        run: |
          python source/preprocess.py -i source/docs/osf-project-metadata-table.md -o OSF/project_metadata_table.md
      - name: commit result
        uses: stefanzweifel/git-auto-commit-action@v4
